export const users = [
  {
    id: 1,
    name: "Sarah Wilson",
    avatar: "SW",
    status: "online",
    lastSeen: "Active now",
    lastMessage: "Thanks for the update!",
    timestamp: "2 min",
    unreadCount: 2,
  },
  {
    id: 2,
    name: "Mike Johnson",
    avatar: "MJ",
    status: "online",
    lastSeen: "Active now",
    lastMessage: "Let's schedule a meeting",
    timestamp: "15 min",
    unreadCount: 0,
  },
  {
    id: 3,
    name: "Emily Davis",
    avatar: "ED",
    status: "away",
    lastSeen: "30 minutes ago",
    lastMessage: "Perfect! See you tomorrow",
    timestamp: "1 hour",
    unreadCount: 1,
  },
  {
    id: 4,
    name: "John Smith",
    avatar: "JS",
    status: "offline",
    lastSeen: "2 hours ago",
    lastMessage: "Could you send me the files?",
    timestamp: "3 hours",
    unreadCount: 0,
  },
  {
    id: 5,
    name: "Lisa Brown",
    avatar: "LB",
    status: "online",
    lastSeen: "Active now",
    lastMessage: "Great work on the project!",
    timestamp: "1 day",
    unreadCount: 0,
  },
];

export const initialMessages = [
  {
    id: 1,
    senderId: 1,
    senderName: "Sarah Wilson",
    message: "Hey! How are you doing today?",
    timestamp: "10:30 AM",
    isOwn: false,
  },
  {
    id: 2,
    senderId: 0,
    senderName: "You",
    message: "Hi Sarah! I'm doing great, thanks for asking. How about you?",
    timestamp: "10:32 AM",
    isOwn: true,
  },
  {
    id: 3,
    senderId: 1,
    senderName: "Sarah Wilson",
    message:
      "I'm wonderful! Just finished the quarterly report. The numbers look really promising this time.",
    timestamp: "10:35 AM",
    isOwn: false,
  },
  {
    id: 4,
    senderId: 0,
    senderName: "You",
    message:
      "That's fantastic news! I'd love to review it when you have a chance.",
    timestamp: "10:37 AM",
    isOwn: true,
  },
  {
    id: 5,
    senderId: 1,
    senderName: "Sarah Wilson",
    message: "Absolutely! I'll send it over right after our meeting.",
    timestamp: "10:38 AM",
    isOwn: false,
  },
  {
    id: 6,
    senderId: 1,
    senderName: "Sarah Wilson",
    message: "Thanks for the update! 🚀",
    timestamp: "10:45 AM",
    isOwn: false,
  },
];
